### ISSUE TITLE
More customization logs is possible?

### ISSUE THREAD

**Issue by pirankashani** [fabric8io/fluent-plugin-kubernetes_metadata_filter#108]
Hello,
I would like to customize my log with more tags. for instance if a log look likes as following:

> {"log":"I1125 11:33:18.947057       1 trace.go:76] Trace[1459855838]: \"Get /api/v1/namespaces/kube-system/endpoints/kube-scheduler\" (started: 2017-11-25 11:33:18.315642294 +0000 UTC) (total time:  631.38115ms):\n","stream":"stderr","time":"2017-11-25T11:33:18.952213987Z"}

I need to arrange it in this way:
`I       = Info`
`1125= 25-Dec`
and other items so on.
and finally it looks like:
Kubernetes.api-server.sevierity = Info
Kubernetes.api-server.time = 11:33:18.947057
Kubernetes.api-server.duration= 631.38115ms
Kubernetes.api-server.date = 2017-11-25
Kubernetes.api-server.pid = 1

Is it possible to edit this project anyhow or I should create a Fork request? What is your idea?

**Comment by richm** [comment]
You'll need a general purpose `in_tail` + custom parser (or if using `in_systemd` a `record_transformer` filter).  That sort of thing isn't the purpose of this plugin.
