### ISSUE TITLE
Customization of metadata prefix

### ISSUE THREAD

**Issue by alexandru-ersenie** [fabric8io/fluent-plugin-kubernetes_metadata_filter#110]
Currently all enriched fields are prefixes with "kubernetes". Example:
`kubernetes.host
kubernetes.labels.release
`
It would be nice to have the option to choose the prefix, and use shortened prefixes, such as "k8s"
`k8s.host
k8s.labels.release`

Can someone point me in the right direction where the metadata is constructed?

**Comment by richm** [comment]
You'll want to add a new config param here: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L38

use it here: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L297

and here: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L325

**Comment by githubskipper** [comment]
All clear, thx for the really quick response. I'll better get to it then

**Comment by jcantrill** [comment]
Closed stale
