### ISSUE TITLE
Use Kubernetes service account and KUBERNETES_SERVICE_{HOST,PORT} for automated configuration

### ISSUE THREAD

**Issue by joshk0** [fabric8io/fluent-plugin-kubernetes_metadata_filter#12]
First of all, good plugin, especially with the JSON parsing -- simple but effective.

Just an idea. Couldn't this plugin, if running within a Kubernetes pod, use the pod service account and host and port environment variables that are automatically provided to every pod to auto-configure API access?

**Comment by jimmidyson** [comment]
That's a good idea. Try those env vars if available, enable enhanced metadata if can successfully query API server?

Would definitely accept a PR for this if you have time.

**Comment by jimmidyson** [comment]
This is done now - thanks!
