### ISSUE TITLE
[Propose] Support decorating metadata by specifying namespace_name, pod_name explicitly

### ISSUE THREAD

**Issue by yantang-msft** [fabric8io/fluent-plugin-kubernetes_metadata_filter#126]
The current implementation works great with the files (console log) and journald scenario.

While I'm thinking about using the plugin in the sidecar scenario, where the main application container send logs directly to the fluentd sidecar container. I don't want to modify my application to add the tag in the special format. Moreover, it would require my application to query the K8s API server since there is no easy way to get the containerId.

However, since fluentd is running in the same pod with my application, it's very easy to pass the namespace_name and pod_name to the sidecar through downward API, which is enough to fetch the pod metadata and enrich the logs of my main application.

I want to get some opinions from you guys. If you think it's a valid scenario, I'd like to contribute a third filtering mode other than files and journald.

**Comment by richm** [comment]
@yantang-msft sure, sounds good

**Comment by jcantrill** [comment]
I'm not sure I really understand your use-case and the need to provide additional filtering modes.  The incoming events include a tag from which the information needed to query for additional meta is determined.  Presumably, if you are able to provide a tag with the same information then there are no modifications required to this plugin.  The regex is configurable [1] so it may only require you to forward a tag in a format that can be configured and consumed by this plugin

[1] https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L49

**Comment by yantang-msft** [comment]
Except for the simplicity of configuration, another benefit of exposing namespace_name and pod_name as config parameters is I only need to watch the changes of a certain pod instead of all pods.

**Comment by yantang-msft** [comment]
@jcantrill I created a PR https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/133 to demonstrate the motivation, i.e., running fluentd as a sidecar. In this case, I only care about the pod that the sidecar is running in.
I didn't add test cases because I would like to get some feedbacks from you first.

**Comment by richm** [comment]
Does https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/155 solve this problem?

**Comment by yantang-msft** [comment]
@richm I have moved my focus on other projects for a long time. After refreshing the memory, I don't think https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/155 is what I was looking for.
Because it's still trying to get the ```namespace_name```, ```pod_name``` using the regex to match the log file name, which works if the application is sending log through console and fluentd monitor the mounted log file. However, I was trying to have my application sending logs directly to fluentd with http.
I can close this issue, looks like I'm the only one trying to set up fluentd like this. :(
