### ISSUE TITLE
Getting plugin error (ElasticSearch aws plugin) while trying to install on fluentd-1.2.1

### ISSUE THREAD

**Issue by Sam123ben** [fabric8io/fluent-plugin-kubernetes_metadata_filter#140]
Hi,

While trying to install aws elastic search plugin on fluentd v1.2.1, I am getting error stating that the plugin is not for the fluentd 1.2.1. ANy specific configureation I need to do or add in order to install aws elastic search plugin to fluentd.

Regards,
Samyak

**Comment by jcantrill** [comment]
Please open issue directly with the plugin author or fluentd
