### ISSUE TITLE
getting lot of logs and no automated way to rotate the same once the logs are pushed to s3

### ISSUE THREAD

**Issue by Sam123ben** [fabric8io/fluent-plugin-kubernetes_metadata_filter#141]
Hi,

I am using s3 plugin in fluentd 1.2.1 version and I see that in a few hours many logs get accumulated inside the /var/log/fluentd-buffer/s3.buffer directory and that results in diskspace crunch issue. Any idea how fluentd can manage and rotate the logs or delete the logs once its pushed to s3.

Any configuration I need to add or update ?

**Comment by jcantrill** [comment]
@Sam123ben This is something I would address directly with fluentd.
