### ISSUE TITLE
Version => 2.1.0 breaks JSON logging in elasticsearch

### ISSUE THREAD

**Issue by monotek** [fabric8io/fluent-plugin-kubernetes_metadata_filter#145]
We us the fluent-plugin-kubernetes_metadata_filter plugin in: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image

After update to version => 2.1.0 the JSON logging is broken.

At least Elasticsearch can't recognize the JSON fields anymore and just gets a simple single logline, without extracting the fields.

With version 2.0.0 of fluent-plugin-kubernetes_metadata_filter everything works fine.

**Comment by richm** [comment]
Correct - https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter
"NOTE: As of the release 2.1.x of this plugin, it no longer supports parsing the source message into JSON and attaching it to the payload. The following configuration options are removed:

    merge_json_log
    preserve_json_log
"

You'll have to use another fluentd filter/parser plugin to do the JSON parsing.  This is how we did it in openshift aggregated logging fluentd: https://github.com/openshift/origin-aggregated-logging/tree/master/fluentd/lib/filter_parse_json_field
https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/filter-parse-json-field.conf

**Comment by monotek** [comment]
Why do you have used an own implementation of json parsing?
Fluentd can do this by its build in filter_parser plugin.
The following config did the trick for me:

`    # Fixes json fields in Elasticsearch
    <filter kubernetes.**>
      @id filter_parser
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>`

**Comment by ervinb** [comment]
@monotek Could you please provide your full config? I'm having difficulties with mine:
```
 <source>
    @type tail
    @id in_tail_container_logs
    path /var/log/containers/*.log
    pos_file /var/log/fluentd-containers.log.pos
    tag kubernetes.* # expands to: kubernetes.var.log.containers.pod_namespace_container.log
    read_from_head true
    <parse>
      @type json
      json_parser json
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </parse>
</source>

<filter kubernetes.**>
  @type kubernetes_metadata
  @id filter_kube_metadata
</filter>

<filter kubernetes.**>
  @id filter_parser
  @type parser
  key_name log
  reserve_data true
  remove_key_name_field false
  <parse>
    @type multi_format
    <pattern>
      format json
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
</filter>
```

The inner JSON is not parsed from the `log` field.

**Comment by monotek** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml
