### ISSUE TITLE
Persistent cache with key timeout for the k8s metadata cache to deal with restarts and pod deletion.

### ISSUE THREAD

**Issue by HackToHell** [fabric8io/fluent-plugin-kubernetes_metadata_filter#149]
Hello,
In the case where there's a very high rate of logs, the push to ES can slow down considerably. In the mean time, if there's a pod created in namespace, then the pod is deleted, the logs for the particular pod is lost because the API server does not have the pod object. 
The caching logic can be modified so that it removed a pod after X amount of time, this also needs to be persistent to the disk because if the pod restarts, we will loose the in memory cache.

I can send a PR for this change, do you have any suggestions/other solutions?

**Comment by jcantrill** [comment]
PR's are always welcome.  There is a balancing act to be considered here with regards to:
* memory usage
* on disk buffer availability
* metadata retention needs.

I would argue that maybe you need to consider expanding the size of your ES cluster if you exceed the limits beyond what is capable with increasing the buffer size [1].  Also, it would be useful if your cache impl could be a drop in replacement for the current LRU cache [2].

[1] https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L41
[2] https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb

**Comment by josephmcasey** [comment]
I recently stumbled upon this problem, and it seems like a functionality gap worth filling. Given the amount of time that has passed from the WIP PR that was never finished. Has a new design come about for addressing this issue that would differs from the WIP PR #157 ?

**Comment by jcantrill** [comment]
Nothing has changed with regards to this issue. I'm not certain when this was created in relation to the cache design change, but the current implementation makes an effort to associate pod meta using time stamps if needed. The reality is that if the info was never fetched then really there is nothing more to associate; meta is only available using pod name and namespace. You can always turn off watch, modify the eviction time and raise the cache count for longer cache availability.  There are currently no plans to add another cache impl. PRs are welcome if you believe there is something that fits your usecase. There is an open PR that provides an alternative cache option that could be used as a starting point.

**Comment by josephmcasey** [comment]
> The reality is that if the info was never fetched then really there is nothing more to associate; meta is only available using pod name and namespace.

I had similar thoughts as you on this matter. My first instinct was that this problem you highlight identifies the need a service that is tangential to what this plugin addresses, so I would love to here your thoughts on said solution even if it isn't completely related to this repository's problem-set.

It seems this plugin would benefit from having access to a type of Kubernetes Graveyard service whereby node/pod metadata is persisted when a pod cycles through a "preStop" hook until the metadata is configured to drop. Thoughts, would this be a library you would be interested in utilizing if it existed?

**Comment by jcantrill** [comment]
Closing due to age
