### ISSUE TITLE
Adding the option to put Kubernetes Metadata to root field

### ISSUE THREAD

**Issue by albertweng13** [fabric8io/fluent-plugin-kubernetes_metadata_filter#153]
Currently the plugin adds an enriched field "kubernetes" with all the metadata. I was looking to implement putting the metadata directly into the root field. This functionality is similar to how journalbeat does the "fields_under_root" flag. Any advice on how to accomplish this?

**Comment by richm** [comment]
You could use a record_transformer plugin to "move" the kubernetes fields to be in the top level of the record then remove the `kubernetes` field.
If you really must have this done in the plugin itself, please submit a PR to add a config param like `fields_under_root`

**Comment by jcantrill** [comment]
Closing issue as stale wont fix
