### ISSUE TITLE
Logs blocked when emit transaction failed: error_class=ArgumentError error="comparison of Time with Fluent::EventTime failed" 

### ISSUE THREAD

**Issue by kkotamar** [fabric8io/fluent-plugin-kubernetes_metadata_filter#162]
Hi,
  We see this error in Fluentd logs sometimes and when this error happens, fluentd stops reading logs.
emit transaction failed: error_class=ArgumentError error="comparison of Time with Fluent::EventTime failed" location="/var/lib/gems/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.4/lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb:53:in 

Below is the configuration we are using.

 <filter kubernetes.**>
                     @type kubernetes_metadata
                     @id kubernetes_metadata
                     ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                     bearer_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
                     cache_size 1000
                     watch false
                     cache_ttl 36000
                     @log_level warn
          </filter>

**Comment by kkotamar** [comment]
Fluentd version is 1.2.1
kubernetes_metadata_filter version 2.1.4

**Comment by richm** [comment]
fixed by https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/160
 kubernetes_metadata_filter version 2.1.5
