### ISSUE TITLE
$['kubernetes']['namespace_name'] : Generating wrong values

### ISSUE THREAD

**Issue by sharmmoh1983** [fabric8io/fluent-plugin-kubernetes_metadata_filter#166]
When using this filter , I am getting following logs

Also logs from container are : `{"log"=&gt;"2019-01-28 05:42:56.633 INFO it works\n", "stream"=&gt;"stdout", "docker"=&gt;{"container_id"=&gt;"acc646a7732d324c38d4547dd45860240f87c14dc42d4d60ab99d6f6405d1035"}, "kubernetes"=&gt;{"container_name"=&gt;"node", "namespace_name"=&gt;"nodetest", "pod_name"=&gt;"node-7f788f67d9-85sfx", "container_image"=&gt;"fluentd-node-sample:latest", "container_image_id"=&gt;"docker://sha256:578d51126f8b60524ec6a1abd3e903916c892ad11e81aaa96161695938d3f5fc", "pod_id"=&gt;"2cad95f2-22bf-11e9-8b7e-08002790fca6", "labels"=&gt;{"app"=&gt;"node", "pod-template-hash"=&gt;"3934492385"}, "host"=&gt;"minikube", "master_url"=&gt;"https://10.96.0.1:443/api", "namespace_id"=&gt;"b7ae48d3-22b3-11e9-8b7e-08002790fca6"}, "kubernetes_namespace_container_name"=**&gt;**"nodetest.node"}`

How to get rid of  **gt** from log files

**Comment by richm** [comment]
Can you do the following: put a `<filter kubernetes.*> @type stdout` before the kubernetes_metadata filter showing that the `&gt;` are not in the record before the filter?  Also, please provide the fluentd version, the ruby version, and your kubernetes_metadata plugin configuration.

**Comment by jcantrill** [comment]
closing stale
