### ISSUE TITLE
newbie q:  How do we access the metadata?

### ISSUE THREAD

**Issue by beth2016** [fabric8io/fluent-plugin-kubernetes_metadata_filter#175]
So, I have this:

>       <filter tail.containers.**>
>         @type kubernetes_metadata
>       </filter>
> 
>       <filter tail.containers.**>
>         @type record_transformer
>         enable_ruby true
>         <record>
>           somevar ${kubernetes["namespace_name"]}
>         </record>
>       </filter>
> 

I am getting this error:
2019-05-20 20:00:29 +0000 [warn]: #0 dump an error event: error_class=RuntimeError error="failed to expand `kubernetes[\"namespace_name\"]` : error = undefined local variable or method `kubernetes' for #<Fluent::Plugin::RecordTransforme
rFilter::RubyPlaceholderExpander::CleanroomExpander:0x00007f5b61c54540>" 

How do I access the fields that kubernetes_metadata populate?

**Comment by richm** [comment]
try
```
      somevar ${record["kubernetes"]["namespace_name"]}

**Comment by beth2016** [comment]
thank you so much.   that works.    Is there a way to check if the variable (namespace_name in this example) exist first?   and if the variable doesnt exist,  set a default?

**Comment by richm** [comment]
```
      somevar ${(record["kubernetes"] && record["kubernetes"]["namespace_name"]) ? record["kubernetes"]["namespace_name"] : "namespace is unknown"}
```

**Comment by beth2016** [comment]
That works.   Much appreciated.    Thank you so so so much.
