### ISSUE TITLE
Few config params not working/supported

### ISSUE THREAD

**Issue by apu1111** [fabric8io/fluent-plugin-kubernetes_metadata_filter#178]
Hi,
In the README.md file, I could see some skip_* config parameters are mentioned but when I configured those under the filter, fluentd is complaining. Wanted to know if I am doing something wrong or those parameters are not supported yet?

### README.md file
![README_MD](https://user-images.githubusercontent.com/50829067/58983923-728b9b80-87f5-11e9-9098-24fb1a4757e9.jpg)

### fluentd log
![logs](https://user-images.githubusercontent.com/50829067/58984025-a9fa4800-87f5-11e9-88ae-c99554425610.jpg)

**Comment by richm** [comment]
> Wanted to know if I am doing something wrong or those parameters are not supported yet?

No, not yet. We haven't released to rubygems.org yet

**Comment by apu1111** [comment]
Thanks for your reply. Any timeline for the release?

**Comment by richm** [comment]
> Thanks for your reply. Any timeline for the release?

no
