### ISSUE TITLE
Routing events for multiple categories of containers

### ISSUE THREAD

**Issue by syst0m** [fabric8io/fluent-plugin-kubernetes_metadata_filter#186]
I want to define distinct parsing configurations for several different categories of containers.
For example, the application containers require nested json parsing of the log field:

```    <filter kubernetes.**>
      @type parser
      format json
      key_name log
      reserve_data true
      hash_value_field parsed
      remove_key_name_field true
      replace_invalid_sequence true
      emit_invalid_record_to_error false
    </filter>
```

However, this filters out all the events from the non-application containers.
There are prometheus, envoy, kube2iam, and similar system containers,
for which I only want to do basic json parsing of the events.

Unfortunately, the application containers do not have a common denominator,
which could be used to tag them based on the log name in `/var/log/containers`.

Is there a way to re-route application and non-applications events, by using tags or labels?

**Comment by richm** [comment]
> Is there a way to re-route application and non-applications events, by using tags or labels?

I think this is not a question specific to this plugin, it's more of a general fluentd question.  I would suggest using the fluentd forums/mailing lists for follow ups.

You would first need some sort of method for distinguishing which logs contain the nested JSON fields you want to parse.  Is there some field or data value in the records that you can use to tell if the record has a nested JSON field you want to parse?  If so, then you could use the rewrite tag filter to retag the records: https://docs.fluentd.org/output/rewrite_tag_filter

**Comment by syst0m** [comment]
@richm All the application logs have a nested `log` field.
I'll give it a go, with the `rewrite_tag_filter`.
Thanks for the pointer!

**Comment by syst0m** [comment]
@richm It looks like the `rewrite_tag_filter` is an output filter
If I understand the fluentd chain of processing correctly, and also according to the usecases and examples provided on the plugin docs, the next step in the chain, after using the plugin,
is to forward the logs.
I guess this wouldn't work in my usecase, since I need to apply a specific nested JSON parsing filter,
to the events, only after their tag would be rewritten.

**Comment by richm** [comment]
> @richm It looks like the rewrite_tag_filter is an output filter

Yes and no.  It is an unusual plugin, and helps to understand how it works.  It works like a `match` for output plugins - once you hit the `rewrite_tag_filter` plugin, processing "ends" - you will not further process any configs that match that tag pattern.  The plugin will change the tag, then resubmit the record again to the top of your processing pipeline, just as if it came from one of your sources.  Or, you can define a specific `label`, and have the  `rewrite_tag_filter` plugin send the records to that label.  You do not have to forward the logs after that step in the chain.  You can send the logs to a nested JSON parsing filter.  No, I don't have an example, but the general fluentd lists/forums/docs should be able to help.

**Comment by syst0m** [comment]
Thanks for the clarification, it is much appreciated.
