### ISSUE TITLE
How to restrict kube-system namespace logs in fluentd to splunk through splunk-connect-for-kubernetes

### ISSUE THREAD

**Issue by shanmukha511** [fabric8io/fluent-plugin-kubernetes_metadata_filter#190]
Hi have added below code to output.conf file but still the kube-system logs reflecting in splunk.
<match kubernetes.var.log.containers.**kube-system**.log>
   @type null
 </match>

**Comment by richm** [comment]
I think you are using the wrong tag format.

**Comment by shanmukha511** [comment]
Can you please assist wt is wrong in format and wt format shld I use ?

**Comment by richm** [comment]
> Can you please assist wt is wrong in format and wt format shld I use ?

The tag format comes from the `in_tail` plugin or whatever your input source is.  Perhaps ask on the fluentd forum.
