### ISSUE TITLE
fluent-plugin-kubernetes_metadata_filter times out periodically when contacting kube-api server resulting in missing labels in GKE

### ISSUE THREAD

**Issue by anymms** [fabric8io/fluent-plugin-kubernetes_metadata_filter#195]
GKE uses Deployment labels to add metadata to a given deployed container. We are seeing missing metadata on our container logs caused by timeouts when the plugin queries the API server. While the logs are collected correctly, the user-defined labels are intermittently absent. Our internal investigation leads us to believe the issue might be the way fluent-plugin-kubernetes_metadata_filter retries after it encounters a 500 response from the kube-api server. 

Example logEntry timeout event:

"textPayload": "  /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/http-0.9.8/lib/http/timeout/null.rb:18:in `open'\n",
    "insertId": "XXXXXXXXXXXXXXX",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "container_name": "fluentd-gcp",
        "namespace_name": "kube-system",
        "location": "[LOCATION]",
        "project_id": "[PROJECT]",
        "cluster_name": "[CLUSTER]",
        "pod_name": "fluentd-gcp-v3.1.1-XXXX"
      }
    },

 template:
    metadata:
      creationTimestamp: null
      labels:
        customLabel1: "value1"
        customLabel2: "value2"
        customLabel3: "value3"

Example container logEntry response without the user-defined labels:

{
 insertId: "XXXXXXXXXXXXXXX"  
 logName: "[PATH]"  
 receiveTimestamp: "2019-09-09T22:10:22.877448338Z"  
 resource: {
  labels: {
   cluster_name: "[CLUSTER_NAME]"    
   container_name: "[CONTAINER_NAME]"    
   location: "[LOCATION]"    
   namespace_name: "[NAMESPACE]"    
   pod_name: "[POD_NAME]"    
   project_id: "[PROJECT]"    
  }
  type: "k8s_container"  
 }
 severity: "ERROR"  
 textPayload: "INFO: xxxxxxxxxxxx branch indexing action completed: SUCCESS in 1.8 sec
"  
 timestamp: "2019-09-09T22:09:02.488196842Z"  
}

Expected behavior: Consistency. I'd like the metadata labels to always be present in the logs. If it is not possible to alter the current timeout handling, I'd expect an error instead of failing silently and reporting incomplete information.

**Comment by arbetts** [comment]
@anymms is there any update for this? we originally contacted GCP about this issue with the GKE and eventually landed here.

any way we can prioritize this since we've been waiting for a fix for this in GKE for a few months now?

**Comment by jcantrill** [comment]
@arbetts There are no guarantees you will always have labels associated with a given log entry.  This plugin uses log meta in to retrieve the labels from the api server.  There is both a caching mechanism and the ability to watch pods in an attempt to stay current with labels associated with a given pod.  Depending upon how quickly fluent processes your logs, you are constantly in a state where the labels you have may or may not be consistent to when the log was generated. I would expect processing of subsequent records would associate the correct meta with a log assuming it:
* has an entry in the cache
* is capable of fetching the labels from the api server
There is no retry mechanism other then subsequent fetches to the API server if there is a cache miss.
