### ISSUE TITLE
Why the record could not be obtained at fluentd 1.7.4 ？

### ISSUE THREAD

**Issue by xidiandb** [fabric8io/fluent-plugin-kubernetes_metadata_filter#200]
my .conf :
```
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    <filter kubernetes.**>
      @type record_modifier
      <record>
        Payload ${record['log']}
        pod_name ${record['kubernetes']['pod_name']}
        container_name ${record['kubernetes']['container_name']}
        namespace_name ${record['kubernetes']['namespace_name']}
      </record>
      whitelist_keys Payload,pod_name,container_name,namespace_name
    </filter>
```
But there are no fields like pod_name,namespace_name in the result,Only field Payload.

**Comment by richm** [comment]
What are the versions of fluentd, this plugin, and other components you are using?
If you run fluentd in debug or verbose mode, do you see any pertinent error messages?

**Comment by xidiandb** [comment]
Forget it. It's my fault.I take the time as the index name,But fluentd set the time at 1970.So I looked at the wrong index.
