### ISSUE TITLE
master branch unit test fails

### ISSUE THREAD

**Issue by rockb1017** [fabric8io/fluent-plugin-kubernetes_metadata_filter#202]
activesupport-3.2.22.5/
addressable-2.7.0/
ast-2.4.0/
bump-0.8.0/
charlock_holmes-0.7.7/
codeclimate-test-reporter-0.6.0/
concurrent-ruby-1.1.5/
cool.io-1.5.4/
copyright-header-1.0.22/
crack-0.4.3/
dig_rb-1.0.1/
docile-1.3.2/
domain_name-0.5.20190701/
escape_utils-1.2.1/
fluentd-1.7.4/
github-linguist-7.6.1/
hashdiff-1.0.0/
http-0.9.8/
http-accept-1.7.0/
http-cookie-1.0.3/
http-form_data-1.0.3/
http_parser.rb-0.6.0/
i18n-0.9.5/
jaro_winkler-1.5.4/
json-2.2.0/
kubeclient-1.1.4/
lru_redux-1.1.0/
mime-types-3.3/
mime-types-data-3.2019.1009/
mini_mime-1.0.2/
minitest-4.7.5/
msgpack-1.3.1/
multi_json-1.14.1/
netrc-0.11.0/
parallel-1.19.1/
parser-2.6.5.0/
power_assert-1.1.5/
public_suffix-4.0.1/
rainbow-3.0.0/
rake-13.0.1/
recursive-open-struct-1.0.0/
rest-client-2.1.0/
rr-1.2.1/
rubocop-0.76.0/
ruby-progressbar-1.10.1/
rugged-0.28.3.1/
safe_yaml-1.0.5/
serverengine-2.2.0/
sigdump-0.2.4/
simplecov-0.17.1/
simplecov-html-0.10.2/
strptime-0.2.3/
test-unit-3.0.9/
test-unit-rr-1.0.5/
tzinfo-2.0.0/
tzinfo-data-1.2019.3/
unf-0.1.4/
unf_ext-0.0.7.6/
unicode-display_width-1.6.0/
vcr-5.0.0/
webmock-3.7.6/
yajl-ruby-1.4.1/

`Error: test: pod MODIFIED cached when hostname matches(DefaultPodWatchStrategyTest)
: NameError: uninitialized constant Kubeclient::Resource
/Users/rbaek/rock/fluent-plugin-kubernetes_metadata_filter/test/plugin/test_watch_pods.rb:32:in `block in <class:DefaultPodWatchStrategyTest>'`

ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin18]

**Comment by rockb1017** [comment]
Is this known test failure or is there something wrong with my env?

**Comment by jcantrill** [comment]
@rockb1017 I have not investigated yet, but to my knowledge the tests are still valid.  I did note the CI is broken but it initially looks to be env related.  Note all the  tests are running with ruby 2.4 or better so maybe runtime related?

**Comment by jcantrill** [comment]
closing as this has been resolved
