### ISSUE TITLE
Where is kubeclient's timeout configured

### ISSUE THREAD

**Issue by xidiandb** [fabric8io/fluent-plugin-kubernetes_metadata_filter#203]
Because our environmental machine is a bit old, timeout occurred while connecting to k8s, causing fluentd to stop.I want to manually set kubeclient's timeout.

**Comment by jcantrill** [comment]
It's created here https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L256 You may need to trace where i actually is set and provide a PR if not exposed
