### ISSUE TITLE
Getting ExitCode out of completed pod

### ISSUE THREAD

**Issue by whm0627** [fabric8io/fluent-plugin-kubernetes_metadata_filter#210]
Hi everyone,

Any recommendations about how to get the exit code out of a completed pod? The need is majorly from a Kubernetes `Job`. 

Also, Often, when a pod got terminated by timeout, there won't be any log entry directly out of that container. 

Thanks in advance

**Comment by jcantrill** [comment]
This is unrelated to the purpose of this plugin which is to provide kubernetes metadata for augmenting container logs.  This kind of information is likely obtainable from the job.status or a completed pod.  Consider reviewing the kubernetes docs or asking in  the kube github issues.
