### ISSUE TITLE
High request rate towards Kubernetes API server

### ISSUE THREAD

**Issue by mszabo** [fabric8io/fluent-plugin-kubernetes_metadata_filter#213]
After upgrading to 2.4.2 I observed high request rate towards our Kubernetes API server.

I believe the reason is the code introduced in #204 

We got the following response for the pod event watch:
```
{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"too old resource version: 201394728 (201675730)","reason":"Gone","code":410}}
```
In this case the connection was closed and no exception raised, therefor the code setting pod_watch back to nil and doing the exponential backoff did not get executed, but instead the thread kept retrying with this old resource version in an endless loop.

I think either type = ERROR case should be handled in the watch.each block here:
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb#L104

or just outside of the watch.each block an exception should be raised to make sure the rescue block gets executed.

What do you think @qingling128 ?

**Comment by jcantrill** [comment]
@mszabo might you be able to submit a patch to address the issue you are describing here?

**Comment by mszabo** [comment]
@jcantrill I am not really familiar with Ruby, but opened a PR which I believe fixes the problem outlined in this issue.
