### ISSUE TITLE
Plugin should return string keys not symbols

### ISSUE THREAD

**Issue by richm** [fabric8io/fluent-plugin-kubernetes_metadata_filter#22]
The plugin returns this::

    {:docker:{:container_id:"46ac488dad3d826d86c1b095c8ea4b0904ee8c8c95e06e5f55571b99e91ee00f"},
     :kubernetes:{:namespace_name":"test",....}
    }

This is not permitted in fluentd: http://docs.fluentd.org/articles/plugin-development#record-format:
"Fluentd plugins assume the record is a JSON so the key should be the String, not Symbol. If you emit a symbol keyed record, it may cause a problem."

    router.emit(tag, time, {'foo' => 'bar'})  # OK!
    router.emit(tag, time, {:foo => 'bar'})   # NG!

This causes problems trying to pass the data through filters.  Specifically, record_transformer cannot reference the keys, either to use them to build other fields in the record, or to remove_keys.

**Comment by richm** [comment]
closed - PR was merged

I've confirmed that the fix works with openshift/origin-aggregated-logging/fluentd

@jimmidyson Are you planning to do another release soon?

**Comment by jimmidyson** [comment]
Thanks for confirming. Yeah I'll release tomorrow.

**Comment by richm** [comment]
Thanks!
