### ISSUE TITLE
The cpu is very high when I use v2.4.5

### ISSUE THREAD

**Issue by xidiandb** [fabric8io/fluent-plugin-kubernetes_metadata_filter#224]
It was normal at first，The CPU went up after a while
![image](https://user-images.githubusercontent.com/12483608/77508352-7af8b400-6ea5-11ea-8f69-2c54f3be4558.png)

**Comment by xidiandb** [comment]
To be honest, using 2.4.2 also has the same problem, using 2.4.1 does not have this problem

**Comment by dsbrng25b** [comment]
It is maybe also worth to mention that the problems do not start right after the start of fluentd. In our case (@yvespp) everything is behaving normally for about 30 minutes and then the number of requests to the API-Server and the CPU-Usage start to increase.

At about 16:50 and 18:10 we restarted/redeployed fluentd.

![image](https://user-images.githubusercontent.com/19696698/77670207-2aa55300-6f86-11ea-86b9-1985b90f511e.png)
![image](https://user-images.githubusercontent.com/19696698/77670179-1cefcd80-6f86-11ea-8b87-a465539596ac.png)

**Comment by mszabo** [comment]
Couple of PRs supposed to fix this issue. All but one are in 2.4.5. It's working good for us with 1.16. What's your Kubernetes version?

**Comment by xidiandb** [comment]
my k8s version is 1.14

**Comment by yvespp** [comment]
1.16.7

**Comment by dsbrng25b** [comment]
I think this problem got introduced here #209 or here [9b48b09](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/9b48b09fa56fcb32c0bcc8e7547bb7589a309125)
@qingling128 can you maybe take a look?

**Comment by qingling128** [comment]
The CPU usage of the watch retries was brought down by https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/214. (Some experiments here: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/214#issuecomment-602249297).

When using 2.4.1, did you observe that the agent crashes and restarts instead when connections are closed? That was the previous behavior we observed before the watch retry implementation. Perhaps we can add a flag to control which action to perform when connections are closed:
1. retry.
2. crash and restart.

Does that make sense?

**Comment by qingling128** [comment]
Something like what was reported in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/194.

**Comment by jcantrill** [comment]
@yvespp @xidiandb Can you please attach your config.  Also, I suspect if you disable "watch" this problem goes away?

**Comment by yvespp** [comment]
Our config is just this:
```
    <filter kubernetes.**.log>
      @type kubernetes_metadata
    </filter>
```

I updated to the latest version and set watch=false. So far CPU and API server requests didn't go up.

**Comment by jcantrill** [comment]
@xidiandb @qingling128 any confirmation if the latest gems have resolved this issue?  Can we close?

**Comment by irizzant** [comment]
I'm having the same problem, audit flooded with `Connection closed early` messages and Prometheus alerting continuously about slow requests for pods and namespaces (we're talking about 1min to get to `ReponseComplete` stage).

This is happening with version 2.7.0 of fluent-plugin-kubernetes_metadata_filter

**Comment by jcantrill** [comment]
> I'm having the same problem, audit flooded with `Connection closed early` messages and Prometheus alerting continuously about slow requests for pods and namespaces (we're talking about 1min to get to `ReponseComplete` stage).
> 
> This is happening with version 2.7.0 of fluent-plugin-kubernetes_metadata_filter

I'm trying to understand if high CPU is related to "watch" being enabled or generally related to processing log messages.

**Comment by jcantrill** [comment]
Closing given we have several releases since this was reported. There were a number of merges related to watch on how that bit is being updated.  Additionally v3.0.0 has some optimizations of interest
