### ISSUE TITLE
Please publish 2.4.6 with fix for `:namespace_watch_retry_count` 

### ISSUE THREAD

**Issue by diclophis** [fabric8io/fluent-plugin-kubernetes_metadata_filter#227]
Hello,

Thank your for all the work so far on this plugin... we are encountering the error with `:namespace_watch_retry_count` that was recently fixed ... but we have not seen the next version published into the gem system yet (we expect to see 2.4.6 with the fix)

If there is anything I or my team can do to help with this please let me know.

Thanks

-Jon

**Comment by iyurev** [comment]
+1

**Comment by jcantrill** [comment]
https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/2.4.6
