### ISSUE TITLE
'orphan' namespace ID in the metadata

### ISSUE THREAD

**Issue by shenmuxiaosen** [fabric8io/fluent-plugin-kubernetes_metadata_filter#234]
Hi,

From the doc, *"If the plugin cannot authoritatively determine the namespace of the container emitting a log record, it will use an 'orphan' namespace ID in the metadata."* We have observed that the orphan namespace happens a lot. So what is the root cause for this plugin not being able to determinate the namespace? 

In the problematic logs, there are pod/container names, but for host and namespace it is null or orphaned, which aligns with the plugin's default behavior. Also the issue is not consistent and it just happened sometime then recovered itself.  One guess is that it needs to talk to Kubernetes API server to fetch the namespace? And then the server is temporarily unavailable. 

Also if we turn off **allow_orphans**, will it just leave namespace and namespace id empty?

**Comment by jcantrill** [comment]
> Hi,
> 
> From the doc, _"If the plugin cannot authoritatively determine the namespace of the container emitting a log record, it will use an 'orphan' namespace ID in the metadata."_ We have observed that the orphan namespace happens a lot. So what is the root cause for this plugin not being able to determinate the namespace?

Pod info is scraped from the container log file name which provides the name of namespace but not its unique id.  This means in a scenario where NS is created, deleted, recreated from the same name and logs still exist on disk, you could potentially be trying to associate meta from the original version of the NS even though its uuid is different then the latest.

The plugin has some logic to try and cache metadata based on ns, podname, uids, and creation dates.  If using this combo of info it is unable to "match" a log entry to a known container, it will fall back to orphan.  If you are creating a number of short lived pods you may be pushing the meta out of the LRU cache.

> 
> In the problematic logs, there are pod/container names, but for host and namespace it is null or orphaned, which aligns with the plugin's default behavior. Also the issue is not consistent and it just happened sometime then recovered itself. One guess is that it needs to talk to Kubernetes API server to fetch the namespace? And then the server is temporarily unavailable.
> 

Correct.  the plugin has to speak to the API server to fetch meta

> Also if we turn off **allow_orphans**, will it just leave namespace and namespace id empty?

I defer this exercise to you by reading the code; I don't recall what the config does.

**Comment by shenmuxiaosen** [comment]
From the [doc](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter#configuration), it says "```allow_orphans``` - Modify the namespace and namespace id to the values of ```orphaned_namespace_name``` and ```orphaned_namespace_id``` when true (default: true)"

So if we set ```allow_orphans``` to be false, it won't use the value of ```orphaned_namespace_name``` and ```orphaned_namespace_id```. Will it just leave namespace empty or put a best guess value there? 

This issue happens in our production cross multiple regions, although only a small portion of logs are affected. I don't think it is due to short lived pods or namespace as the prod deployment is fully controlled and doesn't align with the time when this issue happened. We also have monitors against pod restart/crash.. As you mentioned, the plugin uses a cache for metadata, what will happen if there is a cache miss? Will it fetch data from API server instead?

There are some improvements that we can try like increasing the cache size or change its ttl. Will those fix help this issue?

**Comment by jcantrill** [comment]
> From the [doc](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter#configuration), it says "`allow_orphans` - Modify the namespace and namespace id to the values of `orphaned_namespace_name` and `orphaned_namespace_id` when true (default: true)"
> 
> So if we set `allow_orphans` to be false, it won't use the value of `orphaned_namespace_name` and `orphaned_namespace_id`. Will it just leave namespace empty or put a best guess value there?

I encourage you to review the code for the exact behavior

> 
> This issue happens in our production cross multiple regions, although only a small portion of logs are affected. I don't think it is due to short lived pods or namespace as the prod deployment is fully controlled and doesn't align with the time when this issue happened. We also have monitors against pod restart/crash.. As you mentioned, the plugin uses a cache for metadata, what will happen if there is a cache miss? Will it fetch data from API server instead?
> 
> There are some improvements that we can try like increasing the cache size or change its ttl. Will those fix help this issue?

I encourage you to test
