### ISSUE TITLE
Documentation on default tag regex is wrong

### ISSUE THREAD

**Issue by pranavmarla** [fabric8io/fluent-plugin-kubernetes_metadata_filter#235]
As per the [README](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter), the default regex value for _tag_to_kubernetes_name_regexp_ is: 
`\.(?<pod_name>[^\._]+)_(?<namespace>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$</pod>)`

As far as I can tell, there are 2 issues with this:
1. The regex value listed above is not valid syntax, because there are too many characters at the end -- everything after `$` should be removed.
2. The default regex value listed above does NOT match what appears to be the actual default value in the [code](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L52), which is much stricter:
`var\.log\.containers\.(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$`

**Comment by jcantrill** [comment]
@pranavmarla pull requests are welcome
