### ISSUE TITLE
Enhancement: Reduce noise in logs

### ISSUE THREAD

**Issue by pranavmarla** [fabric8io/fluent-plugin-kubernetes_metadata_filter#236]
This is an enhancement/feature request, not a bug.

**Context**
By default, every 30 seconds, this plugin prints the following log:
`2020-06-11 20:31:57 +0000 [info]: #0 stats - namespace_cache_size: 3, pod_cache_size: 2, id_cache_orphaned_record: 15, namespace_cache_api_updates: 17, pod_cache_api_nil_bad_resp_payload: 15, id_cache_miss: 17, pod_cache_watch_misses: 19, pod_cache_watch_ignored: 3, pod_cache_watch_delete_ignored: 3, pod_cache_api_updates: 2`

While I can see how this might be useful for the maintainers of this plugin, or for users who are more knowledgeable than me, frankly this means nothing to me -- looking at the sample log above, I have no idea what it means, or whether it's good/bad.
Worse, because it is printed as part of the default _INFO_ log level **_every 30 seconds_**, it absolutely floods my Fluentd logs, and makes it way harder to spot actual errors amidst all that noise.

**Enhancement Request**
For now, I have 'fixed' this by changing the log level of this plugin to _WARN_ -- however, that now means I might be missing some actually important _INFO_ log just to get rid of this (to me) meaningless debug log.
Also, just in general, having the default behaviour be to print out this detailed debug info as part of the regular _INFO_ log level, every 30 seconds, seems like overkill for most users.

Please consider changing the default behaviour of this plugin so that this log is re-classified as a _DEBUG_ log -- thus, maintainers/users who want this info can still access it by changing the plugin's log level to _DEBUG_, but the average user (like myself) isn't bombarded with this stuff out of the box.

**Comment by nvtkaszpir** [comment]
try to add `@log_level warn` to filter section.

**Comment by pranavmarla** [comment]
@nvtkaszpir Thanks -- as mentioned above, I've already done that as a workaround. The suggestion here is to change the default behaviour so that that workaround is not required, since this type of detailed, frequent log behaviour is more suited for a DEBUG log level anyway, not INFO.

**Comment by jcantrill** [comment]
Consider raising the stats interval to a more agreeable value: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L71
