### ISSUE TITLE
Namespace annotations still present in the output when deleted from kubernetes

### ISSUE THREAD

**Issue by julienlefur** [fabric8io/fluent-plugin-kubernetes_metadata_filter#238]
When an annotation is deleted on a namespace, it is not deleted from the output. 

https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/940296bac92ac05b97654e156dcf16c1eacd21b5/lib/fluent/plugin/kubernetes_metadata_common.rb#L34-L38

Test:
1. Configure a regex for match annotation
2. add an annotation on a namespace
- the cache is updated --> monitoring the stats : namespace_cache_watch_updates
- the new annotation is correctly handled and added
3. remove the same annotation on the namespace
- the cache is marked as updated  --> monitoring the stats : namespace_cache_watch_updates
- but the annotation is still visible in the output 

My configuration:
```
<filter kubernetes.**>
  @type kubernetes_metadata
  @id filter_kube_metadata
  annotation_match ["prefix.*"]
  skip_master_url true
  de_dot false
</filter>
```

Version:
kubernetes_metadata_filter: 2.4.6

**Comment by jcantrill** [comment]
Pull requests are welcome

**Comment by jcantrill** [comment]
Closing due to age.  Please reopen if still an issue (or submit a PR)
