### ISSUE TITLE
Add 410 Gone handling for namespace watch

### ISSUE THREAD

**Issue by Ghazgkull** [fabric8io/fluent-plugin-kubernetes_metadata_filter#246]
Similar to the issue we fixed last week for pod watches (#226), we should also gracefully handle 410 Gone errors on the namespace watch.

**Comment by Ghazgkull** [comment]
@jcantrill I've submitted a PR which fixes this issue, https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/247.

If this PR looks good to you and we can get a new version of this plugin pushed soon, I already have a PR open for the fluend-es-image in the Kubernetes project and I'd be happy to get this fix included there so it's available to everyone. (https://github.com/kubernetes/kubernetes/pull/93116/)

**Comment by jcantrill** [comment]
released in https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/2.5.2
