### ISSUE TITLE
formatting does not match ruby standards

### ISSUE THREAD

**Issue by grosser** [fabric8io/fluent-plugin-kubernetes_metadata_filter#251]
would you accept a PR that makes everything be 2-space indent etc minor fixes ?

**Comment by jcantrill** [comment]
Yes.  Might we add a linter or pre-commit hook to format such that it meets ruby standards?

**Comment by grosser** [comment]
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/264
