### ISSUE TITLE
make K8S_NODE_NAME required when in kubernetes

### ISSUE THREAD

**Issue by grosser** [fabric8io/fluent-plugin-kubernetes_metadata_filter#257]
not setting K8S_NODE_NAME results in slow/big requests to `pods` list, which can harm the api server and the stability of the whole cluster, would you accept a PR to make it required when in kubernetes (via env var detection for example) ?
atm someone just installing the plugin without reading the whole readme can stumble into this bug and it's pretty nasty :(
... can have an opt-out for weird setups

**Comment by jcantrill** [comment]
> not setting K8S_NODE_NAME results in slow/big requests to `pods` list, which can harm the api server and the stability of the whole cluster, would you accept a PR to make it required when in kubernetes (via env var detection for example) ?

Is this to restrict the list of items being "watched"?

**Comment by grosser** [comment]
mostly to restrict the pod list request which can get very expensive when the cluster is large
