### ISSUE TITLE
fluent-plugin-kubernetes_metadata_filter has requirements to 0.12 fluentd and not 0.14 fluentd

### ISSUE THREAD

**Issue by Kuckkuck** [fabric8io/fluent-plugin-kubernetes_metadata_filter#26]
fluent-plugin-kubernetes_metadata_filter.gemspec is pinning to fluentd 0.12 and not to the new release 0.14. Could you please check, if it is working with 0.14?

Thanks

Olaf

**Comment by jimmidyson** [comment]
We've actually been running with the 0.14 alpha totally fine. Fancy sending in a PR with the update to gemspec?

**Comment by jimmidyson** [comment]
This should now be fixed with 0.23.0, released to rubygems.org.
