### ISSUE TITLE
change filter_stream to filter

### ISSUE THREAD

**Issue by grosser** [fabric8io/fluent-plugin-kubernetes_metadata_filter#263]
I wrote some other plugins and alway used filter, so wanted to check which is best and https://docs.fluentd.org/filter#filter-chain-optimization says to not use filter_stream ... is there any reason to keep it or can it be changed as long as the tests pass ?

**Comment by jcantrill** [comment]
> I wrote some other plugins and alway used filter, so wanted to check which is best and https://docs.fluentd.org/filter#filter-chain-optimization says to not use filter_stream ... is there any reason to keep it or can it be changed as long as the tests pass ?

I defer to you here.  I know of no reason it needs to be implemented as-is.  Refactoring is acceptible IMO:

* if it makes the code more readable
* tests continue to pass
* It meets recommended plugin guidelines

**Comment by cosmo0920** [comment]
From this PR's benchmark, using filter chain optimization makes around 10 ~ 20% faster than using `#filter_stream`.

But I have no idea that using `#filter` method improves code readability and continue to pass unit tests.

**Comment by grosser** [comment]
I started using https://github.com/grosser/fluent-plugin-kubelet_metadata so no longer working on this, can close if nobody else wants it.
