### ISSUE TITLE
Add annotations

### ISSUE THREAD

**Issue by ash2k** [fabric8io/fluent-plugin-kubernetes_metadata_filter#27]
I have a usecase where I cannot put some specific information into a label because it contains "invalid" characters. So I'd like to put it into an annotation but this plugin does not add annotations to the record. Would be nice to have such support (behind a flag? only annotations with listed names or names that match a regex?).

**Comment by jimmidyson** [comment]
Sounds like a good idea. I'd be happy to receive a PR that matches annotation keys against a regex.

**Comment by galanoff** [comment]
Pull request #31 was proposed. It would be awesome if you could release a new version after the PR is merged. Thanks!

**Comment by jimmidyson** [comment]
@galanoff Of course! Once it's merged...

**Comment by galanoff** [comment]
Hi Jimmy,

Just a reminder. Could you please take a look at pull request  #31 ?

**Comment by jesseolsen** [comment]
Looks like this issue can be closed, now that #31 merged...

**Comment by jimmidyson** [comment]
Thanks!
