### ISSUE TITLE
label with match for containers not working

### ISSUE THREAD

**Issue by pabrahamusa** [fabric8io/fluent-plugin-kubernetes_metadata_filter#270]
I have a config with labels and match as below. I want to label the same message with two different label names and match the contents again for one label before writing to kafka. However if i change the match criteria it stops working. I want to match a specific container name for the label. If I revert the match condition  it will work. I am assuming the label with match is somewhere causing the issue. Anyone came across something similar before?

```
  <match kubernetes-in.var.log.containers.al-**>
      @type copy
      copy_mode deep
      <store>
        @type relabel
        @label @dmzenv
      </store>
      <store>
        @type relabel
        @label @alllogs
      </store>
    </match>

   ## The below is working fine
    <label @alllogs>
      <match kubernetes-in.var.log.containers.al-**>
        @type kafka2
       xxxxxxx
      </match>
    </label>

   ## below is not working and I am trying to filter by container name al-dmzenv-** with namespace .
  ## if i change the match condition to kubernetes.var.log.containers.al-** this will also work.
    <label @dmzenv>
      <match kubernetes.var.log.containers.al-dmzenv-**_namespace_**>
        @type kafka2
       xxxxxxxx
      </match>
    </label>
```

**Comment by jcantrill** [comment]
Please address your question to a more general fluentd forum as this is not specific to this plugin

**Comment by pabrahamusa** [comment]
Managed to fix this, Thanks for closing.
