### ISSUE TITLE
jsonpath requires Ruby version >= 2.5

### ISSUE THREAD

**Issue by shanalily** [fabric8io/fluent-plugin-kubernetes_metadata_filter#271]
An image build that worked just yesterday with ruby version 2.4.10 is now failing with:

```
ERROR: Error installing fluent-plugin-kubernetes_metadata_filter-2.3.0.gem: 
 jsonpath requires Ruby version >= 2.5. 
```

This seems similar to #184 

Is this a dependency issue that can be fixed?

**Comment by shanalily** [comment]
Support for ruby versions < 2.5 was [dropped in jsonpath v1.0.6](https://github.com/joshbuddy/jsonpath/commit/ccfb39be456c88f4961e96f981e154936a537782) which is a [runtime dependency for kubeclient](https://rubygems.org/gems/kubeclient/versions/4.8.0) (I think it's only used for [gcp command credentials](https://github.com/abonas/kubeclient/blob/56c55d9469d739159a771dba5656610540223ff8/lib/kubeclient/gcp_command_credentials.rb))

**Comment by hidalgopl** [comment]
I'm experiencing same issue. This is my build script:
```bash
curl -sfL https://toolbelt.treasuredata.com/sh/install-ubuntu-bionic-td-agent3.sh | sh
sudo sed -i '/^User=.*$/d' /lib/systemd/system/td-agent.service
sudo sed -i '/^Group=.*$/d' /lib/systemd/system/td-agent.service
sudo apt-get install -y g++ make
sudo /opt/td-agent/embedded/bin/fluent-gem install --version 0.7.4 fluent-plugin-cloudwatch-logs
sudo /opt/td-agent/embedded/bin/fluent-gem install --version 2.3.0 fluent-plugin-concat
sudo /opt/td-agent/embedded/bin/fluent-gem install --version 2.5.1 fluent-plugin-grok-parser
sudo /opt/td-agent/embedded/bin/fluent-gem install --version 1.0.2 fluent-plugin-json-in-json-2
sudo /opt/td-agent/embedded/bin/fluent-gem install --version 2.2.0 fluent-plugin-kubernetes_metadata_filter
```
which produces:
```
==> amazon-ebs: + sudo /opt/td-agent/embedded/bin/fluent-gem install --version 2.4.0 fluent-plugin-kubernetes_metadata_filter
==> amazon-ebs: ERROR:  Error installing fluent-plugin-kubernetes_metadata_filter:
==> amazon-ebs: 	jsonpath requires Ruby version >= 2.5.
```
@shanalily did you managed to workaround this?

**Comment by jcantrill** [comment]
Feel free to create a PR against the v2.3.0 tag and I'll be more then happy to create a branch from that PR.  Closing otherwise WONTFIX
