### ISSUE TITLE
Support for fluentd-1.12

### ISSUE THREAD

**Issue by mrueg** [fabric8io/fluent-plugin-kubernetes_metadata_filter#272]
Currently https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/fluent-plugin-kubernetes_metadata_filter.gemspec#L19 limits fluentd to <1.12 

Is there any breaking change in fluentd 1.12 that would stop the plugin from working?

**Comment by jcantrill** [comment]
https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/2.6.0
