### ISSUE TITLE
Metadata fails to be filtered if tag includes `-`

### ISSUE THREAD

**Issue by AppleMaster** [fabric8io/fluent-plugin-kubernetes_metadata_filter#279]
Following the example configuration, like so:
```
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /tmp/fluentd-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag taggytag-prod.*
  format json
  read_from_head true
</source>

<filter taggytag-prod.var.log.containers.**.log>
  @type kubernetes_metadata
</filter>
```

I expect this to source from our container logs and then append the kubernetes_metadata to the message before being matched and, in our case, sent to a RabbitMQ cluster.
Instead, with trace level logging on, I can see that the plugin mangles up the key for the message like so:
`,: key => taggytag - prod.var.log.containers.node - exporter - zmr5x_monitoring_node - exporter - 50 d4a6bd57842433557e7bdf0307eb02a8b513b2e87c3a0e299faf7c1c0e7405.log: headers => {
    "timestamp" => "2021-01-26 17:08:57 UTC"
}`

resulting in the kubernetes_metadata never actually manifesting in our sent logs.

We resolved this by changing our initial tag to a single string, without the `-` involved - but that seems less than ideal.
Can a fix be implemented or is there advice to architect around this issue?

**Comment by jcantrill** [comment]
@AppleMaster can you provide a sample of the record or the full pathname of the file?  It appears the key may not be in th expected format and does not match the regex

**Comment by jcantrill** [comment]
Closing as this plugin is only capable of fetching pod info if it has a namespace and podname to use for query.  This is parsed out of the container file path.  I would suggest not altering the tag until after it is handled by this filter.
