### ISSUE TITLE
some abnormal log lack some fields

### ISSUE THREAD

**Issue by AkitoZz** [fabric8io/fluent-plugin-kubernetes_metadata_filter#336]
when is use fluentd(1.3.3) with metadata_filter plugin(2.4.1), i met some trouble and i dont know how does it caused.
this picture shows a piece of abnormal log that lacked "pod_name" and "container_image" fields
![Uploading 1061653996834_.pic.jpg…]()

and this picture show a normal log, it has "pod_name" and "container_image" fields
![Uploading 1051653996834_.pic.jpg…]()

 How this condition arises and how could i fix it, thx

**Comment by jcantrill** [comment]
namespace, pod_name and depending upon which path is being followed containername/container_hash are fields that are discoverable by the filename which becomes the tag passed to the plugin.  These are the minimum bits one could have if the API call fails.  container_image requires a successful API call.  If you are not getting pod_name it is likely incoming tag is not coming from a valid kubernetes locations which would be `/var/log/pods` or `/var/log/containers`
