### ISSUE TITLE
Permit to use Fluentd v1.15.0

### ISSUE THREAD

**Issue by cosmo0920** [fabric8io/fluent-plugin-kubernetes_metadata_filter#339]
In the end of June, we have released Fluentd v1.15.0.
But this k8s metadata filter plugin does not permit to use with it.
Still left in Fluentd v1.14.0 world.

Could you release the new version which can work with Fluentd v1.15.0?

**Comment by jcantrill** [comment]
https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/2.12.0
