### ISSUE TITLE
[info]: [filter_kube_metadata] Exception encountered parsing namespace watch event. The connection might have been closed. Sleeping for 1 seconds and resetting the namespace watcher.error reading from socket: Connection reset by peer

### ISSUE THREAD

**Issue by jeffreyrubi** [fabric8io/fluent-plugin-kubernetes_metadata_filter#351]
Version: [v1.15-debian-azureblob-1]

The filter starts throwing this Exception Info recently. I've checked the ClusterRole and ClusterRoleBinding. Confirmed that the fluentd has been granted action to namespaces and pods.

Need advice how this can be fixed?

**Comment by jcantrill** [comment]
This appears maybe its an issue related to these configuration parameters: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L53-L54 introduced as part of https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/350

**Comment by jcantrill** [comment]
Closing due to age.  Please reopen as needed
