### ISSUE TITLE
watch_retry_interval & watch_retry_exponential_backoff_base are not documented

### ISSUE THREAD

**Issue by fmad** [fabric8io/fluent-plugin-kubernetes_metadata_filter#356]
Are they safe to use still or should they be avoided?

**Comment by jcantrill** [comment]
They are "documented" here: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L88-L93   I would not consider the README an authoritative source
