### ISSUE TITLE
is a changelog maintained anywhere?

### ISSUE THREAD

**Issue by mmerickel** [fabric8io/fluent-plugin-kubernetes_metadata_filter#360]
Right now I need to stare at ruby diffs and git commits to get a sense of changes between releases. This is ok-ish for the point releases but I'm pretty worried about going from v2 to v3 without some explicit docs?

**Comment by jcantrill** [comment]
There is no maintained change log.  Breaks between any major versions have mostly been to remove functionality that should really have never been added to this plugin (e.g. dedot labels).  Frankly the majority of changes over the last several years has been to address points of concern that are not of concern to the plugin.

**Comment by jcantrill** [comment]
I believe this commit does a good job of summarizing https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/4171b98932104bd4cefc740b056f2f7cd169a052
