### ISSUE TITLE
410 Gone encountered. Restarting pod watch to reset resource versions

### ISSUE THREAD

**Issue by olyhao** [fabric8io/fluent-plugin-kubernetes_metadata_filter#362]
When fluentd collects business logs, [filter_kubernetes_metadata] 410 Gone encountered. Restarting pod watch to reset resource versions.410 Gone error appears. This problem is fatal to me. How to solve this problem, thank you

**Comment by olyhao** [comment]
![image](https://user-images.githubusercontent.com/41614895/212063577-b94c5bf1-0679-42e1-9fe0-a25c3cc0b391.png)
This is my version, what do I need to configure to solve this problem

**Comment by olyhao** [comment]
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/41614895/212065686-478572d5-5eb4-4c82-a5cc-c5fc82ad6509.png">

**Comment by olyhao** [comment]
![image](https://user-images.githubusercontent.com/41614895/212218348-75ef6fe4-0c46-4177-ac02-ba743802cd7d.png)
Thank you for your reply; yesterday, my fluentd agent suddenly stopped collecting logs, and the fluentd agent log shows only: {"message":"[filter_kubernetes_metadata] 410 Gone encountered. Restarting pod watch to reset resource versions.410 Gone"}
  [info]: #0 [filter_kubernetes_metadata] 410 Gone encountered. Restarting pod watch to reset resource versions.410 Gone; this kind of error, I restart the fluentd agent to restart the log collection work, but restarting the pod can not completely solve my problem , this kind of operation is not advisable in the production environment; I can only get these log information. Is there any relationship between the fluentd agent stopping log collection and the 410 error? How can I go about solving this to avoid fluentd from stopping log collection；need your help very much，thank！！！

**Comment by olyhao** [comment]
> > fluentd收集业务日志时，遇到[filter_kubernetes_metadata] 410 Gone。重新启动 pod watch 以重置资源版本。出现 410 Gone 错误。这个问题对我来说是致命的
> 
> 请更具体一点。这对您的日志处理有何不利影响。410 错误意味着需要重建 watch 客户端，以便插件可以继续接收回调以保持其缓存同步。可以完全禁用手表；我鼓励您查看有关如何执行此操作的配置选项。
![image](https://user-images.githubusercontent.com/41614895/212219142-ae70404f-8803-4d59-9a16-2f848d22dde6.png)

Thank you for your reply; yesterday, my fluentd agent suddenly stopped collecting logs, and the fluentd agent log shows only: {"message":"[filter_kubernetes_metadata] 410 Gone encountered. Restarting pod watch to reset resource versions.410 Gone"}
[info]: #0 [filter_kubernetes_metadata] 410 Gone encountered. Restarting pod watch to reset resource versions.410 Gone; this kind of error, I restart the fluentd agent to restart the log collection work, but restarting the pod can not completely solve my problem , this kind of operation is not advisable in the production environment; I can only get these log information. Is there any relationship between the fluentd agent stopping log collection and the 410 error? How can I go about solving this to avoid fluentd from stopping log collection；need your help very much，thank！！！

**Comment by jcantrill** [comment]
My first suggestion would be to turn off the watch completely and see if the issue persists.  You could additionally increase  the verbosity of the plugin to see if there is additional information that may be useful.

Turning off the watch means the cache will be built by making calls to the api server when an entry is not found instead of it being dynamically populated as pods come and go on the node.  The cache is an LRU which is configured to expire entries based on max entries or time.  Disabling the watch may be the best option unless you can provide more information to track down your issue.

I do not see how rebuilding the watch would block messages from flowing unless there is a bug which causes the client to indefinitely hang.  The watch is intended to be re-established and continue as normal

**Comment by olyhao** [comment]
> 我的第一个建议是完全关闭手表，看看问题是否仍然存在。您还可以增加插件的详细程度，以查看是否有可能有用的其他信息。
> 
> 关闭监视意味着缓存将通过在未找到条目时调用 api 服务器来构建，而不是随着 pod 在节点上来来去去动态填充。缓存是一个 LRU，它被配置为根据最大条目数或时间使条目过期。除非您可以提供更多信息来追踪您的问题，否则禁用手表可能是最佳选择。
> 
> 我看不出重建手表会如何阻止消息流动，除非存在导致客户端无限期挂起的错误。手表旨在重新建立并继续正常

Thank you for your answer; I would also like to ask if I turn on the "watch false" configuration when there are many pods, will the pressure on the apiserver service be great?

**Comment by jcantrill** [comment]
I can not speak to what behavior you will encounter for your usecase.  The cache is configured for 1000 entries and 3600s expiration time.  This means assuming the number of pods are consistent on any given node, you should see an early spike and then limited queries as pods come and go.  If you are collecting logs from a build server where pods are short lived, then I would expect the load against the API server to increase given you are likely to evict entries from the cache more frequently.
