### ISSUE TITLE
gemfile.lock fluentd version in v2.13.0

### ISSUE THREAD

**Issue by dombisza** [fabric8io/fluent-plugin-kubernetes_metadata_filter#363]
Hi,

we have been using kubernetes_metadata_filter v2.13.0 with fluentd 1.15.3 and It's working fine. 
fluentd 1.15.0 is defined in the gemfile.lock in the v2.13.0 version of the plugin.

Is it possible to raise that to 1.15.3 since there are no breaking changes between fluentd 1.15.0 -> 1.15.3 ?

thanks in advance.

**Comment by dombisza** [comment]
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/docker-image/v1.15/debian-cloudwatch/Gemfile#L20

**Comment by jcantrill** [comment]
Are you able to upgrade to https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/3.2.0 ?
