### ISSUE TITLE
Compatibility with Ruby >= 3 ? 

### ISSUE THREAD

**Issue by xuoja-acc** [fabric8io/fluent-plugin-kubernetes_metadata_filter#365]
Hi,

We have been using kubernetes_metadata_filter in fluentd 1.14 and until now it was working fine!

We tried to upgrade to fluentd 1.16 and fluent-plugin-kubernetes_metadata_filter 3.1.3 with ruby 2.7.8 and it is also working fine but when we try to upgrade to ruby 3.0.6 ou 3.1.4 : the plugin is very very slow and consume a lot of CPU.

Have you tried/test this plugin on ruby >= 3 ? Is it compatible?

Ruby 2.7 has reach EOL since 2023-03-31 -> https://www.ruby-lang.org/en/downloads/branches/

Thanks in advance.

**Comment by jcantrill** [comment]
I have built a version of fluent we use for our project on ruby 3.1 using the latest version of this plugin and it functionally works to my satisfaction.  We have yet to do any additional performance testing so I can not comment if or why its performance characteristics have changed.
