### ISSUE TITLE
How to debug problem if kubernetes_metadata not add any metadata from k8s?

### ISSUE THREAD

**Issue by SomeAkk** [fabric8io/fluent-plugin-kubernetes_metadata_filter#367]
Init:
- i use containerd (maybe it make some problems)
- i change tag after i read log from /var/log/comtainers

My fluentd config (part with kubernetes_metadata):
```
<source>
  @type tail
  path "/var/log/containers/my-app*.log"
  pos_file "/var/log/fluentd-containers.log.pos"
  read_from_head true
  tag "my_app"
  <parse>
    @type cri
  </parse>
</source>
<filter my_app>
  @type kubernetes_metadata
</filter>
<filter my_app>
  @type record_transformer
  enable_ruby true
  <record>
    test_that_no_any_kubernetes_field ${record.to_json}
  </record>
</filter>
```

I try to check if all works good at record_transformer - create "debug field" named `test_that_no_any_kubernetes_field`.
In that field no any kuberenetes metadata(

Is there any way to debug in what i got problem?

**Comment by jcantrill** [comment]
See the README:

...Records from kubernetes containers encode metadata about the container in the file name...
