### ISSUE TITLE
v2.x release with fluentd 1.16.x support

### ISSUE THREAD

**Issue by mrueg** [fabric8io/fluent-plugin-kubernetes_metadata_filter#370]
Can you create a v2.x release with support for fluentd-1.16.x?

Unfortunately we rely on the functionality (https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/320) removed in v3.x and it would be super helpful to have a v2.14.0 released with support for fluentd 1.16.

**Comment by jcantrill** [comment]
dedot functionality was removed because you can accomplish the same thing with other filters or plugins; its usage in this plugin is orthogonal to its purpose.  I don't see the motivation to release another version to support this behavior when it can be accomplished by other means

**Comment by mrueg** [comment]
Thanks, I understand your point. 
I was hoping you'd be okay to support v2.x a bit longer. I'm happy to send a PR to a branch that branches of the latest v2.13.0 release, if this helps.

**Comment by jcantrill** [comment]
Pull requests are always welcome, but what is blocking you from modifying your configuration ? We accomplish this [now](https://github.com/openshift/cluster-logging-operator/blob/release-5.7/internal/generator/fluentd/conf_test.go#L537) using record modifier.  It may performs faster using a [filter](https://github.com/lunardial/fluent-plugin-dedot_filter)
