### ISSUE TITLE
New version of the plugin

### ISSUE THREAD

**Issue by forselli-stratio** [fabric8io/fluent-plugin-kubernetes_metadata_filter#373]
Hi, since https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/48648ff91697e0bd5bfbfdbc5292fb27f448f7f0 was merged, can we get a new version of the plugin with this feature. Documentation is already updated so it would be nice to have the new version of the plugin. Thanks!

**Comment by jcantrill** [comment]
https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/3.3.0
