### ISSUE TITLE
can add  "Controlled By" field to meta 

### ISSUE THREAD

**Issue by gao4263** [fabric8io/fluent-plugin-kubernetes_metadata_filter#377]
kubectl describe pod  can get "Controlled By" of pod , but the plugin can't get this info.  would you have plan to add this feature

**Comment by jcantrill** [comment]
This information looks to come from the pod ownerReference which is an internal accounting mechanism.  I would encourage you to embrace kubernetes [recommendations](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) and label the workload to allow you to associate resources with labels that are meaningful to you.  There is no intent at this time to add this meta
