### ISSUE TITLE
Fluentd and kubeclient with kubernetes_metadata_filter

### ISSUE THREAD

**Issue by ShishirSaxena1002** [fabric8io/fluent-plugin-kubernetes_metadata_filter#392]
I am getting below

fluentd -c /fluentd/etc/fluent.conf
2024-11-05 02:53:05 +0000 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
2024-11-05 02:53:05 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2024-11-05 02:53:05 +0000 [info]: gem 'fluentd' version '1.17.1'
2024-11-05 02:53:05 +0000 [info]: gem 'fluent-plugin-datadog' version '0.14.4'
2024-11-05 02:53:05 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '3.5.1'
#<Thread:0x00007f926b833830 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-3.5.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:119:in `rescue in start_namespace_watch': start_namespace_watch: Exception encountered setting up namespace watch from Kubernetes API v1 endpoint https://10.96.0.1:443/api: wrong number of arguments (given 2, expected 1) (Fluent::ConfigError)
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-3.5.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:110:in `start_namespace_watch'
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-3.5.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:32:in `set_up_namespace_thread'
/usr/local/bundle/gems/json-2.7.4/lib/json/common.rb:222:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)

      Parser.new(source, opts).parse
                 ^^^^^^^^^^^^
        from /usr/local/bundle/gems/json-2.7.4/lib/json/common.rb:222:in `new'
        from /usr/local/bundle/gems/json-2.7.4/lib/json/common.rb:222:in `parse'
        from /usr/local/bundle/gems/kubeclient-4.12.0/lib/kubeclient/common.rb:560:in `format_response'
        from /usr/local/bundle/gems/kubeclient-4.12.0/lib/kubeclient/common.rb:359:in `get_entities'
        from /usr/local/bundle/gems/kubeclient-4.12.0/lib/kubeclient/common.rb:229:in `block (2 levels) in define_entity_methods'
        from /usr/local/bundle/gems/kubeclient-4.12.0/lib/kubeclient/common.rb:101:in `method_missing'
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-3.5.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:128:in `get_namespaces_and_start_watcher'
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-3.5.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:111:in `start_namespace_watch'
        from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-3.5.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:32:in `set_up_namespace_thread'
2024-11-05 02:53:05 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="start_namespace_watch: Exception encountered setting up namespace watch from Kubernetes API v1 endpoint https://10.96.0.1:443/api: wrong number of arguments (given 2, expected 1)"

**Comment by jcantrill** [comment]
> Upgrading the json gem from 2.7.4 to 2.8.2 fixes this

You'll need to be more specific here.  Pull requests are always welcome

**Comment by jcantrill** [comment]
Closing as this issue looks to be unrelated to this plugin. The call stems from kubeclient and the gem dependency in question appears to be provided by the runtime environment
