### ISSUE TITLE
How to create a rule to filter logs by k8s labels?

### ISSUE THREAD

**Issue by kayrus** [fabric8io/fluent-plugin-kubernetes_metadata_filter#40]
I.e. I have k8s labels and I'd like to apply some filter on logs which relate to these labels:

``` json
    "kubernetes": {
      "namespace_name": "default",
      "pod_id": "397f9943-83de-11e6-9679-525400d2e1e2",
      "pod_name": "app-primary-3029120254-rb5u3",
      "container_name": "my-primary-app",
      "labels": {
        "app": "app",
        "app": "primary",
        "pod-template-hash": "3029120254"
      },
      "host": "ubuntu3"
```

And I'd like to remove ANSI colors from these logs:

```
<label %what_should_i_put_here?% >
    type color_stripper
    strip_fields log
</label>
```

**Comment by gamkiller77** [comment]
i have something simulare where I need to have a label value passed to fluentD from the node level.  We mark our nodes as production and non-production and we like to know what life cycle the logs came from.

**Comment by Kuckkuck** [comment]
+1

**Comment by jimmidyson** [comment]
Take a look at http://docs.fluentd.org/v0.12/articles/out_rewrite_tag_filter (specifically http://docs.fluentd.org/v0.12/articles/out_rewrite_tag_filter#rewriterulen-required-at-least-one). I think you can rewrite the tag based on the contents of the record and then do whatever you need to do with more rules, filter, etc.

**Comment by kayrus** [comment]
consider closed. I've implemented lots of use cases in my repo: https://github.com/kayrus/elk-kubernetes/

**Comment by jimmidyson** [comment]
@kayrus That's awesome! Thanks!
