### ISSUE TITLE
Invalid container_id when container of the pod was restarted

### ISSUE THREAD

**Issue by kayrus** [fabric8io/fluent-plugin-kubernetes_metadata_filter#41]
Few days ago a faced a problem with skydns. Its healthcheck resulted in kube2sky container restart. Twice. When I analyzed logs in Kibana I was confused because logs tell that kube2sky was restarted, but container id was the same. Until I noticed the log tag which tells that actual container id was changed. Here is the screenshot.

Original container ID was **fa206692f400f634c7b1546d88a4a110a975782ef28e2f141ce928534b002273** then after restart it was changed to **88dcb977a7fae920ce86725da86295545bed317950048c3a302dfec04fda5c2b** and after next restart it was changed to **165f3844607afd71f2477eed37b2cf50d74931869c2fb7259eafb9bc744e7275**
![screenshot_20161004_171358](https://cloud.githubusercontent.com/assets/4047483/19080152/6f504938-8a56-11e6-903d-ac02eb6076aa.png)

I use fluent-plugin-kubernetes_metadata_filter 0.24.0 which is proposed by [kubernetes repo](https://github.com/kubernetes/kubernetes/blob/3a42ec0b1df55c5ce96fe4e5c5c1b9fb0037f2c0/cluster/addons/fluentd-elasticsearch/fluentd-es-image/build.sh#L33).

**Comment by jcantrill** [comment]
This looks like maybe an old log was processed and new metadata was attached to it.  The caching mechanism has changed since issue was logged.  Closing issue as stale.  Please reopen a new issue with details if required.
