### ISSUE TITLE
Cache isn't invalidated in case where Namespace is deleted and recreated < 1 min apart

### ISSUE THREAD

**Issue by ewolinetz** [fabric8io/fluent-plugin-kubernetes_metadata_filter#42]
pods created under the recreated namespace maintain the namespace UUID from the deleted namespace.

kubernetes v1.3.0+52492b4
openshift v3.3.0.34

**Comment by jimmidyson** [comment]
Happy to get a PR on this. I think there are some other issues with caching that need addressing but someone working on a PR will probably notice & fix those easily enough.

**Comment by jcantrill** [comment]
this should be addressed by #93
