### ISSUE TITLE
Add docker image to metadata

### ISSUE THREAD

**Issue by bcorijn** [fabric8io/fluent-plugin-kubernetes_metadata_filter#54]
Hi,

Would it be possible to add the docker image name:tag to the metadata? It is available from kube pod information and the container_name and container_id are already known from the log. This would allow to trace logs back to specific versions of pods/applications/containers in fast-moving environments, quite a valuable addition in my opinion.

I've looked through the code (I'm not a very experienced ruby developer) and it looks to me like this could be added without too much issues, but I'm not familiar enough to take a stab without getting some feedback where and how this would be best implemented..

**Comment by mblaschke** [comment]
Created a pull request with this feature.
The code is fetching the information from `status.containerStatuses` and uses the container ID for lookup of the information.

Informations published:
- `kubernetes.container_image`
- `kubernetes.container_image_id`

If the information cannot be found (caching issues or what ever happend) the image will be logged as `unknown`.
