### ISSUE TITLE
plugin doesn't work if the logs are not in var/log/containers

### ISSUE THREAD

**Issue by smenon78** [fabric8io/fluent-plugin-kubernetes_metadata_filter#55]
We deploy fluentd as a container and mount the logs from host machine /var/log/containers to fluent container at /containerlogs. This location wouldn't match the regex and plugin doesn't work, or if we have a custom path for container logs is there a way?

**Comment by vinceferro** [comment]
We're having the same issue on brand new k8s installation

**Comment by resnostyle** [comment]
Today I started trying to use: 
> kubernetes_url - URL to the API server. Set this to retrieve further kubernetes metadata for logs from kubernetes API server
as I thought that would bridge the gap, but it doesnt seem to work for me.

**Comment by richm** [comment]
Were you aware that you can change the default regexp used?
```
    config_param :tag_to_kubernetes_name_regexp,
                 :string,
                 :default => 'var\.log\.containers\.(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$'
```

**Comment by resnostyle** [comment]
In our particular case, the directory /var/lib/docker/containers/ contains a directory: "ecac0189ff21a91ede89fcc11340c2" inside it, we find ecac0189ff21a91ede89fcc11340c2-json.log file which is our logs as expected.

In order for fluentd to correlate the container id to an actually container name, my belief is fluentd would need to contact kube api or some other authoritative source to be able to determine the meta_data.

**Comment by richm** [comment]
hmm - I thought it was kubernetes that created the /var/log/containers/*.log files, which includes some of the container/pod/namespace metadata in the log file name.  The plugin was designed to work with the above.  I'm not sure how else you would get that metadata into fluentd.

**Comment by richm** [comment]
Can we close this issue?

**Comment by resnostyle** [comment]
Yes
