### ISSUE TITLE
Option to specify merge key (equivalent of parser.hash_value_field)

### ISSUE THREAD

**Issue by Bekt** [fabric8io/fluent-plugin-kubernetes_metadata_filter#64]
With `merge_json_log true` the keys are merged as top-level keys. This is not always the desirable output as (1) some keys can collide (docker, kubernetes) and (2) it is not ideal for indexing.

It would be nice if the plugin could implement the equivalent of fluentd's parser filters [hash_value_field](http://docs.fluentd.org/v0.12/articles/filter_parser#hashvaluefield) so that the parsed values are stored in a specified field.

### Current
input: `{log: "{\"level\": 10, \"msg\": \"foo\"}}`

output:
```
{
  "log": "{...}",
  "level": 10,
  "msg": "foo",
  "stream": "stdout", 
  "docker": {...},
  "kubernetes": {...}
}
```

### Suggested
`hash_value_field parsed`

input: `{log: "{\"level\": 10, \"msg\": \"foo\"}}`

output:
```
{
  "log": "{...}",
  "parsed": {
    "level": 10,
    "msg": "foo"
  }
  "stream": "stdout", 
  "docker": {...},
  "kubernetes": {...}
}
```

Thoughts? I can probably do a PR sometime this week if it sounds good and you guys don't have a bandwidth.

**Comment by gmile** [comment]
Would absolutely love to have this feature.

**Comment by richm** [comment]
Actually, I would rather have this json parsing feature _completely removed from this plugin_.  There are better ways to do this, rather than having it done as an unrelated side effect of getting kubernetes metadata.

**Comment by gmile** [comment]
@richm true. I got very confused initially about the json being parsed automatically. It took me a while before I figured it out.

**Comment by jcantrill** [comment]
Closing as we intend to remove 'merge_json_log' from this plugin.
