### ISSUE TITLE
prerequisites to use this plugin 

### ISSUE THREAD

**Issue by hiscal2015** [fabric8io/fluent-plugin-kubernetes_metadata_filter#66]
Hi, 

Any prerequisites to use this plugin? Do I have to run td-agent inside of Kubernetes cluster? I want to run td-agent outside of Kubernetes and without specify Kubernetes api since I don't need additional metadata or tags.

**Comment by richm** [comment]
@hiscal2015 If you don't need additional metadata then why do you want to use this filter?
