### ISSUE TITLE
[feature] Add cluster information in meta-data enrichment

### ISSUE THREAD

**Issue by boeboe** [fabric8io/fluent-plugin-kubernetes_metadata_filter#69]
Hi all,

I'd like to be able to see kubernetes.cluster-info (cluster kubernetes master URL would be sufficient) information in the extra fields added by this plugin. The reason is that in a multi-cluster setup, it is currently impossible to determine this information from the enriched data.

Also added a question in the upstream kubeclient repo: https://github.com/abonas/kubeclient/issues/245

**UPDATE:** I have created a pull request to add this feature:
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/70

BR,
Bart

**Comment by jcantrill** [comment]
fixed by #70
