### ISSUE TITLE
[feature] Add namespace labels

### ISSUE THREAD

**Issue by mikebryant** [fabric8io/fluent-plugin-kubernetes_metadata_filter#75]
We have metadata on namespaces that we'd love to have in the log entries

**Comment by jesseolsen** [comment]
This is similar to #67 which I created.  See the Pull Request I put up for it.  You can probably do something very similar...  Hope this helps...

**Comment by mikebryant** [comment]
Thanks :). I did have a look, then when I started trying to change things I ended up with #76 instead.

I'm currently working on combining your PR with my refactoring, and adding labels from namespaces and caching support
