### ISSUE TITLE
not seeing pod labels in log messages

### ISSUE THREAD

**Issue by jchauncey** [fabric8io/fluent-plugin-kubernetes_metadata_filter#8]
Im only getting the `namespace`, `pod`, and `container_name`.

**Comment by jimmidyson** [comment]
Adding labels to logs requires configuring the `kubernetes_url` for the plugin, along with any other seucrity configuration detailed in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter#configuration.

If you have already added that configuration & still don't get the labels then that's a bug.

**Comment by jchauncey** [comment]
where in fluent.conf do these configs go? in the filter section or source?

**Comment by jimmidyson** [comment]
Filter section

**Comment by jchauncey** [comment]
k got it  working =) thanks

**Comment by jimmidyson** [comment]
Brilliant! Thanks for letting me know.
