### ISSUE TITLE
Don't work at K8s 1.6.x RBAC 

### ISSUE THREAD

**Issue by tianctrl** [fabric8io/fluent-plugin-kubernetes_metadata_filter#81]
I create serviceAccount , es cluster worked fine.
But fluentd doesn't running. 
` error="Exception encountered fetching metadata from Kubernetes API endpoint: 403 Forbidden"`
What should I do with this error, please?

**Comment by y-batsianouski** [comment]
Hello, @tianctrl !
Did you fixed it? Maybe you have example of RBAC policy?

Thank you in advance!
