### ISSUE TITLE
How to match logs from specific containers?

### ISSUE THREAD

**Issue by albertvaka** [fabric8io/fluent-plugin-kubernetes_metadata_filter#82]
Hi there!

This plugin is helping us a lot with our logging :) Thanks! Now, I would like to filter out logs from some specific containers, but I haven't found how. I'm completely new to fluentd and I don't fully understand the td-agent.conf syntax, so sorry if this is a silly question :D

I would like to add something like this on top of my td-agent.conf:
```
<match kubernetes.container_name=="my_super_spamy_deployment">
  @type null
</match>
```

But of course that's invalid syntax. How can we achieve something like that?

**Comment by ewolinetz** [comment]
your match statement would be done using wildcard expansion.
If "my_super_spammy_deployment" was a namespace it would be something like: 
```
<match **_spammynamespace_**>
  @type null
</match>
```

`**` will match anything (including delimiters)
`*` will not include delimiters

Hope that helps

**Comment by albertvaka** [comment]
Will that match any key, though? That could lead to a false positives (eg: a log line like `The user 'my user name is spammynamespace' has logged in to my awesome service` would match). I know exactly which field I would like to match against, can't I specify that somehow?

**Comment by ewolinetz** [comment]
That match is only performed on the record's tag [1] not the contents of the log message itself. The tag is based on the kubernetes pod information that includes the namespace, pod name, and container id.

[1] https://docs.fluentd.org/v0.12/articles/config-file#2-ldquomatchrdquo-tell-fluentd-what-to-do

**Comment by albertvaka** [comment]
Thanks a lot! I found the tag for the spammy container to follow the pattern `kubernetes.var.log.containers.my-spammy-container**`, so I'm matching that now :) Closing the issue!
