### ISSUE TITLE
fluentd log is filled up with KubeClient messages

### ISSUE THREAD

**Issue by nhosoi** [fabric8io/fluent-plugin-kubernetes_metadata_filter#84]
We are getting lots of fluentd log messages from Kubeclient::Common::WatchNotice like this.

#<Kubeclient::Common::WatchNotice type="MODIFIED", object={:kind=>"Namespace", :apiVersion=>"v1", :metadata=>{...}, :spec=>{...}, :status=>{:phase=>"Active"}}>

It looks the message is coming from the "puts notice" line in start_namespace_watch (filter_kubernetes_metadata.rb).
```
    def start_namespace_watch
      resource_version = @client.get_namespaces.resourceVersion
      watcher          = @client.watch_namespaces(resource_version)
      watcher.each do |notice|
        puts notice
        ^^^^^^^^^^^
        case notice.type
          when 'MODIFIED'
            cache_key = notice.object['metadata']['name']
            cached    = @namespace_cache[cache_key]
            if cached
              @namespace_cache[cache_key] = parse_namespace_metadata(notice.object)
            end
```
Could you consider eliminating the "puts notice" line or replacing it with the lower log level such as "log.debug(notice)"?  Thanks.

**Comment by vvk** [comment]
Proposed by #80.

**Comment by vvk** [comment]
Though #80 is closed already, it think that this still should be logged at `debug` level, because it's not good to lose such events.

**Comment by jcantrill** [comment]
Closing as no longer see this in the master code branch
