### ISSUE TITLE
Restricting API calls to a single namespace

### ISSUE THREAD

**Issue by bgagnon** [fabric8io/fluent-plugin-kubernetes_metadata_filter#88]
Consider a `DaemonSet` in namespace `friday` whose `spec.serviceAccountName` is set to `fluentd`.
The `ServiceAccount` is named `fluentd` and lives in the same namespace.

    $ kubectl get sa -n friday
    NAME      SECRETS   AGE
    default   1         4d
    fluentd   1         2h

A `Role` named `fluentd` is created in the same namespace:

```yaml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
````

A `RoleBinding` is also created in the same namespace:

```yaml
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
subjects:
- kind: ServiceAccount
  name: fluentd
  apiGroup: ""
roleRef:
  kind: Role
  name: fluentd
  apiGroup: ""
```

We can confirm the RBAC setup is working as expected:

```
$ kubectl auth can-i list pods --as system:serviceaccount:friday:fluentd --namespace friday
yes
```

The current namespace is fed to the fluentd pods via a `POD_NAMESPACE` environment variable:

```yaml
      containers:
      - name: fluentd-es
        image: gcr.io/google-containers/fluentd-elasticsearch:v2.0.1
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

Which allows the fluentd `<source>` looks for log files in the current namespace:

```
    <source>
      type tail
      path "/var/log/containers/*_#{ENV['POD_NAMESPACE']}_*.log"
      pos_file "/var/log/es-containers.#{ENV['POD_NAMESPACE']}.log.pos"
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>
```

The problem is that the `kubernetes_metadata` plugin always queries pods at the cluster level, which fails due to the limited permissions of the service account:

```
2017-10-24 17:49:06 +0000 [info]: reading config file path="/etc/fluent/fluent.conf"
2017-10-24 17:49:06 +0000 [info]: starting fluentd-0.12.39 without supervision
2017-10-24 17:49:06 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.5'
2017-10-24 17:49:06 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.27.0'
2017-10-24 17:49:06 +0000 [info]: gem 'fluent-plugin-prometheus' version '0.3.0'
2017-10-24 17:49:06 +0000 [info]: gem 'fluent-plugin-systemd' version '0.0.8'
2017-10-24 17:49:06 +0000 [info]: gem 'fluentd' version '0.12.39'
2017-10-24 17:49:06 +0000 [info]: adding match pattern="fluent.**" type="null"
2017-10-24 17:49:06 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2017-10-24 17:49:07 +0000 [info]: adding match pattern="**" type="elasticsearch"
2017-10-24 17:49:07 +0000 [error]: config error file="/etc/fluent/fluent.conf" error="Exception encountered fetching metadata from Kubernetes API endpoint: 403 Forbidden (User \"system:serviceaccount:friday:fluentd\" cannot list pods at the cluster scope.)"
```

The plugin should allow limiting its watches to one or more namespaces. This is a use case for shared clusters where tenants are given separate namespaces and want to deploy fluentd logging in the scope of their own namespace.

**Comment by jcantrill** [comment]
@bgagnon Would it be acceptable to watch a single namespace.  To my knowledge, watch clients only allow for you to watch the cluster or a single namespace but not a subset.  Please correct me if you know otherwise.

**Comment by bgagnon** [comment]
> Would it be acceptable to watch a single namespace

Yes, that would fit my use case perfectly.

**Comment by mirwan** [comment]
Hi
I would be interested in that too!
@jcantrill Is this enhancement planned soon? Would a PR help ?
@bgagnon Have you found some workaround since then ?

**Comment by jcantrill** [comment]
> Hi
> I would be interested in that too!
> @jcantrill Is this enhancement planned soon? Would a PR help ?

There is no immediate plan that I know of.  Pull requests are always welcome.

> @bgagnon Have you found some workaround since then ?

**Comment by akhy** [comment]
no progress since last year... guess there's not enough interest in this specific use case 🤔 

Any hint where to look? I might be able to help

**Comment by jcantrill** [comment]
> no progress since last year... guess there's not enough interest in this specific use case 
> 
> Any hint where to look? I might be able to help
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb#L29

I don't have specifics about the client so I don't have an understanding about additional arguments to restrict the namespace.

**Comment by bgagnon** [comment]
For those still looking for this feature, we've switched over from Fluentd to Filebeat which has this feature: https://www.elastic.co/guide/en/beats/filebeat/current/add-kubernetes-metadata.html

In Filebeat's implementation, it retrieves pod metadata from the Kubernetes API server but only for the current node (and, optionally, for the given namespace). Which makes a lot of sense for a logging daemonset, because the pods can only be found on that node.

**Comment by jcantrill** [comment]
Pod meta is now restricted by node.  Further restricting my namespace doesn't make sense IMO unless the node also restricts namespaces since pods from any given namespace can be scheduled on a node.  Closing . Please submit a PR if demand and usecase warrants restricting my namespace.
