### ISSUE TITLE
error_class=NoMethodError error="undefined method `debug' for #<String:0x00000002970c28>" tag="kubernetes.var.log.containers..."

### ISSUE THREAD

**Issue by richm** [fabric8io/fluent-plugin-kubernetes_metadata_filter#99]
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L394

`log` is overloaded here.  `log` should refer to the Logger, not the log message.  Please use a different variable for the log message e.g. `message`.

We also need a test for this case e.g. provide a message with a `log` field that has a JSON parsing error.
@jcantrill

**Comment by jcantrill** [comment]
fixed by #98
